# AllCops:
#   Exclude:
#     - db/schema.rb

Documentation:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Max: 120

NumericLiterals:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
