development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('DB_NAME') { 'survey' } %>
  pool: 5
  username: <%= ENV.fetch('DB_USER') { 'vader' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'this_is_a_secure_password' } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { '5432' } %>

test:
  <<: &development
  username: <%= ENV['DB_TEST_USER'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>
